CREATE TABLE PRICES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID BIGINT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRIORITY BIGINT NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL DEFAULT 'EUR',
    FOREIGN KEY (BRAND_ID) REFERENCES BRAND(ID)
);

CREATE INDEX IDX_PRICES_QUERY ON PRICES (BRAND_ID, PRODUCT_ID, START_DATE, END_DATE);
CREATE INDEX IDX_PRICES_PRIORITY ON PRICES (PRIORITY);
